cart/urls.py
from django.urls import path 

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail_view, name='cart_detail'),
    path('add_cart/<int:product_id>', views.add_product_to_cart, name='add_to_cart'),
    path('remove_cart/<int:product_id>', views.remove_from_cart, name='remove_from_cart'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    
    # Allauth
    path('accounts/', include('allauth.urls')),
    
    # Rosetta
    path('rosetta/', include('rosetta.urls')),
]

pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('contact_us/', views.ContactUsPageView.as_view(), name='contact_us'),
]

product/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product_details'),
    path('comment/<int:product_id>/', views.CommentCreateView.as_view(), name='comment_create'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

cart/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from django.utils.translation import gettext as _ # we use this function to translate 
from django.utils import timezone

class Product(models.Model):
    PRODUCT_STARS = [
        ('1' , _('very bad')),
        ('2' , _('bad')),
        ('3' , _('normal')),
        ('4' , _('good')),
        ('5' , _('perfect')),
    ]

    title = models.CharField(_('Title'), max_length=100)
    text = models.TextField()
    price = models.PositiveIntegerField(default=0)
    active = models.BooleanField(_('Active'), default=True)
    star = models.CharField(choices=PRODUCT_STARS , max_length=5, verbose_name=_('Star'),)
    
    datetime_created = models.DateTimeField(_('Create'), default=timezone.now)
    datetime_modified = models.DateTimeField(_('Modified'), auto_now=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('product_details', args=[self.pk])


class Comment(models.Model):
    PRODUCT_STARS = [
        ('1' , _('very bad')),
        ('2' , _('bad')),
        ('3' , _('normal')),
        ('4' , _('good')),
        ('5' , _('perfect')),
    ]
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', verbose_name=_('Product'),)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments', verbose_name=_('Author'),)
    body = models.TextField(verbose_name=_('Body'))
    star = models.CharField(choices=PRODUCT_STARS , max_length=5, verbose_name=_('Star'),)
    
    datetime_created = models.DateTimeField(verbose_name = _('datetime created'), default=timezone.now)
    datetime_modified = models.DateTimeField(verbose_name = _('datetime modified'), auto_now=True)
    
    active = models.BooleanField(verbose_name = _('active'), default=True)


    def get_absolute_url(self):
        return reverse('product_details', args=[self.product.id])
    

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm , UserCreationForm

from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username')

cart/forms.py
from django import forms

class AddProductToCart(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]    
    
    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

product/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body', 'star',]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .forms import AddProductToCart
from .cart import Cart
from product.models import Product

def cart_detail_view(request):
    cart = Cart(request)
    
    for item in cart:
        item['inplace_product_quantity'] = AddProductToCart(initial={
            'quantity': item['quantity'],
            'inplace': True,
        })
    
    return render(request, 'cart/cart_detail.html', {'cart': cart})

def add_product_to_cart(request, product_id):
    cart = Cart(request)
    
    product = get_object_or_404(Product, id=product_id)
    
    cart_form = AddProductToCart(request.POST)
    
    if cart_form.is_valid():
        cleaned_data = cart_form.cleaned_data
        
        quantity = cleaned_data['quantity']
        
        replace_current_quantity = cleaned_data['inplace']
        
        cart.add_to_cart(product, quantity, replace_current_quantity)
    
    return redirect('cart:cart_detail')

def remove_from_cart(request, product_id):
    cart = Cart(request)
    
    product = get_object_or_404(Product, id=product_id)

    cart.remove_from_cart(product)
        
    return redirect('cart:cart_detail')

pages/views.py
from django.shortcuts import render

from django.views import generic

from product.models import Product

class HomePageView(generic.ListView):
    model = Product
    template_name = 'home.html'
    context_object_name = 'products'


class ContactUsPageView(generic.TemplateView):
    template_name = 'contact_us.html'

product/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.contrib import messages

from .forms import CommentForm
from .models import Product, Comment
from cart.forms import AddProductToCart

class ProductListView(generic.ListView):
    # We use queryset for add or change something that are in our databases in our code
    queryset = Product.objects.filter(active=True)
    paginate_by = 4
    template_name = 'products/product_list.html'
    context_object_name = 'products'


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'products/product_details.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['comment_form'] = CommentForm()
        
        context['add_to_cart'] = AddProductToCart()

        return context


class CommentCreateView(generic.CreateView):
    model = Comment
    form_class = CommentForm
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        
        product_id = self.kwargs['product_id']
        obj.product = get_object_or_404(Product, id=product_id)
                
        messages.success(self.request, _('comment created successfully.' ))         

        return super().form_valid(form)
        

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}

{% load i18n %}

{% block title %}

    {% trans "cart" %}

{% endblock %}

{% block body %}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="{% url 'home' %}">{% trans "Home"%}</a>
                <a class="breadcrumb-item text-dark" href="{% url 'product_list' %}">{% trans "Shop"%}</a>
                <span class="breadcrumb-item active">{% trans "Shopping Cart"%}</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    {% if cart %}
        <div class="row px-xl-5">
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-light table-borderless table-hover text-center mb-0">
                    <thead class="thead-dark">
                        <tr>
                            <th>{% trans "Products"%}</th>
                            <th>{% trans "Price"%}</th>
                            <th>{% trans "Quantity"%}</th>
                            <th>{% trans "Total"%}</th>
                            <th>{% trans "Remove"%}</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        {% for item in cart %}
                            <tr>
                                <td class="align-middle"><img src="img/product-1.jpg" alt="" style="width: 50px;">{{ item.product_info.title }}</td>
                                <td class="align-middle">{% trans "$"%}{{ item.product_info.price }}</td>
                                <td class="align-middle">
                                    <div class="input-group  mx-auto" style="width: 100px;">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-primary btn-minus" >
                                            <i class="fa fa-minus"></i>
                                            </button>
                                        </div>
                                        <input type="text" class="form-control form-control-sm border-0 text-center" value="{{ item.quantity }}">
                                        <div class="input-group-btn">
                                            <button class="btn btn-sm btn-primary btn-plus">
                                                <i class="fa fa-plus"></i>
                                            </button>
                                        </div>
                                    </div>
                                </td>
                                <td class="align-middle">{% trans "$" %} {{ item.total_price }}</td>
                                <td class="align-middle"><a href="{% url "cart:remove_from_cart" item.product_info.id %}" class="btn btn-sm btn-danger" type"submit"><i class="fa fa-times"></i></a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="col-lg-4">
                <form class="mb-30" action="">
                    <div class="input-group">
                        <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">{% trans "Apply Coupon"%}</button>
                        </div>
                    </div>
                </form> 
                <h5 class="section-title position-relative text-uppercase mb-3"><span class="">{% trans "Cart Summary"%}</span></h5>
                <div class="bg-light p-30 mb-5">
                    <div class="border-bottom pb-2">
                        <div class="d-flex justify-content-between mb-3">
                            <h6>{% trans "Subtotal"%}</h6>
                            <h6>{{ cart.get_total_price }} {% trans "$" %}</h6>
                        </div>
                        <div class="d-flex justify-content-between">
                            <h6 class="font-weight-medium">{% trans "Shipping"%}</h6>
                            <h6 class="font-weight-medium">$10</h6>
                        </div>
                    </div>
                    <div class="pt-2">
                        <div class="d-flex justify-content-between mt-2">
                            <h5>{% trans "Total"%}</h5>
                            <h5>$160</h5>
                        </div>
                        <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">{% trans "Proceed To Checkout"%}</button>
                    </div>
                </div>
            </div>
        </div>
    {% else  %}
        <p> {% trans " Cart is empty! Please add some products to the cart. "%}
        <br>
        <a href="{% url 'product_list' %}">{% trans " Go shopping "%}</a>
    {% endif %}
</div>
<!-- Cart End -->


{% endblock %}

pages/templates/contact_us.html
contact_us

product/templates/products/product_list.html
{% extends '_base.html' %}

<!-- Django Tags -->
{% load i18n %}

<!-- Third Party Tags -->
{% load crispy_forms_tags %}

{% block title %}

    {% trans "Product List" %}

{% endblock %}

{% block body %}

<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="{% url 'home' %}">{% trans "Home" %}</a>
                <a class="breadcrumb-item text-dark" href="{% url 'product_list' %}">{% trans "products List" %}</a>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Shop Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-4">
            <!-- Price Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="">{% trans "Filter by price"%}</span></h5>
            <div class="bg-light p-4 mb-30">
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="price-all">
                        <label class="custom-control-label" for="price-all">All Price</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-1">
                        <label class="custom-control-label" for="price-1">$0 - $100</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-2">
                        <label class="custom-control-label" for="price-2">$100 - $200</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-3">
                        <label class="custom-control-label" for="price-3">$200 - $300</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="price-4">
                        <label class="custom-control-label" for="price-4">$300 - $400</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="price-5">
                        <label class="custom-control-label" for="price-5">$400 - $500</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Price End -->
            
            <!-- Color Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="">{% trans "Filter by color"%}</span></h5>
            <div class="bg-light p-4 mb-30">
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="color-all">
                        <label class="custom-control-label" for="price-all">All Color</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-1">
                        <label class="custom-control-label" for="color-1">Black</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-2">
                        <label class="custom-control-label" for="color-2">White</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-3">
                        <label class="custom-control-label" for="color-3">Red</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="color-4">
                        <label class="custom-control-label" for="color-4">Blue</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="color-5">
                        <label class="custom-control-label" for="color-5">Green</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Color End -->

            <!-- Size Start -->
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="">{% trans "Filter by size"%}</span></h5>
            <div class="bg-light p-4 mb-30">
                <form>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" checked id="size-all">
                        <label class="custom-control-label" for="size-all">All Size</label>
                        <span class="badge border font-weight-normal">1000</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-1">
                        <label class="custom-control-label" for="size-1">XS</label>
                        <span class="badge border font-weight-normal">150</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-2">
                        <label class="custom-control-label" for="size-2">S</label>
                        <span class="badge border font-weight-normal">295</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-3">
                        <label class="custom-control-label" for="size-3">M</label>
                        <span class="badge border font-weight-normal">246</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between mb-3">
                        <input type="checkbox" class="custom-control-input" id="size-4">
                        <label class="custom-control-label" for="size-4">L</label>
                        <span class="badge border font-weight-normal">145</span>
                    </div>
                    <div class="custom-control custom-checkbox d-flex align-items-center justify-content-between">
                        <input type="checkbox" class="custom-control-input" id="size-5">
                        <label class="custom-control-label" for="size-5">XL</label>
                        <span class="badge border font-weight-normal">168</span>
                    </div>
                </form>
            </div>
            <!-- Size End -->
        </div>
        <!-- Shop Sidebar End -->


        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-8">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">
                        <div>
                            <button class="btn btn-sm btn-light"><i class="fa fa-th-large"></i></button>
                            <button class="btn btn-sm btn-light ml-2"><i class="fa fa-bars"></i></button>
                        </div>
                        <div class="ml-2">
                            <div class="btn-group">
                                <button type="button" class="btn btn-sm btn-light dropdown-toggle" data-toggle="dropdown">{% trans "Sorting"%}</button>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">{% trans "Latest"%}</a>
                                    <a class="dropdown-item" href="#">{% trans "Popularity"%}</a>
                                    <a class="dropdown-item" href="#">{% trans "Best Rating"%}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% for product in products %}
                    <div class="col-lg-4 col-md-6 col-sm-6 pb-1">
                        <div class="product-item bg-light mb-4">
                            <div class="product-img position-relative overflow-hidden">
                                <img class="img-fluid w-100" src="img/product-1.jpg" alt="">
                                <div class="product-action">
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-shopping-cart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="far fa-heart"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                                    <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-search"></i></a>
                                </div>
                            </div>
                            <div class="text-center py-4">
                                <a class="h6 text-decoration-none text-truncate" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                <div class="d-flex align-items-center justify-content-center mt-2">
                                    <h5>{% trans "$"%}{{ product.price }}</h5><h6 class="text-muted ml-2"><del>$123.00</del></h6>
                                </div>
                                <div class="d-flex align-items-center justify-content-center mb-1">
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small class="fa fa-star text-primary mr-1"></small>
                                    <small>{{ product.star }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <div class="col-12">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center mt_3">
                            {% if page_obj.has_previous %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.previous_page_number}}">{% trans "Previous"%}</a>
                                </li>
                            {% endif %}
                            <li class="page-item">
                                <a class="page-link" href="#">1</a>
                            </li>
                            {% if page_obj.has_next %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ page_obj.next_page_number}}">{% trans "Next"%}</a>
                                </li>
                            {% endif %}
                        </ul>
                    </nav>
                
                </div>
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->


{% endblock %}

templates/_base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <![endif]-->
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="">

    <!-- Favicon -->
    <link href="{% static "img/favicon.ico" %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">  

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static "lib/animate/animate.min.css" %}" rel="stylesheet">
    <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">

  
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


  </head>
  <body dir='rtl'>

    {% include "top_header.html" %}
    
    {% if messages %}
      <div class="container">
          {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}
      </div>
    {% endif %}
    
    {% block body %}

    {% endblock %}

    {% include "footer.html" %}

    {% comment %} <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
    <script src="" async defer></script> {% endcomment %}


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top" style="display: inline;">
      <i class="fa fa-angle-double-up"></i>
    </a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static "lib/easing/easing.min.js"%}"></script>
    <script src="{% static "lib/owlcarousel/owl.carousel.min.js"%}"></script>

    <!-- Contact Javascript File -->
    <script src="{% static "mail/jqBootstrapValidation.min.js"%}"></script>
    <script src="{% static "mail/contact.js"%}"></script>

    <!-- Template Javascript -->
    <script src="{% static "js/main.js"%}"></script>

    <!-- ************************* JS Files ************************* -->

    <!-- jQuery JS -->
    <script src="{% static "js/vendor.js"%}"></script>

    <!-- Main JS -->
    <script src="{% static "js/main.js"%}"></script>

  </body>
</html>